CREATE DATABASE library_db;

CREATE TYPE Gender AS ENUM ('Male', 'Female', 'Others');
CREATE TYPE MemberStatus AS ENUM ('Active', 'Suspended');
CREATE TYPE FulfillmentStatus AS ENUM ('Fulfilled', 'Pending', 'Processing');

CREATE TABLE IF NOT EXISTS Authors (
	AuthorID BIGSERIAL PRIMARY KEY NOT NULL,
	AuthorName VARCHAR(100) NOT NULL,
	CountryOfOrigin VARCHAR(100) NOT NULL,
	NumberOfBooksWritten INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Books (
	BookID INTEGER PRIMARY KEY NOT NULL,
	Title VARCHAR(100) NOT NULL,
	AuthorID INTEGER REFERENCES Authors(AuthorID) ON DELETE SET NULL,
	Genre VARCHAR(100) NOT NULL,
	DateOfPublication DATE NOT NULL,
	Publisher VARCHAR(100) NOT NULL,
	ISBN VARCHAR(100) NOT NULL,
	Language VARCHAR(100) NOT NULL,
	AvailableCopies INTEGER NOT NULL,
	AgeRating VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS Members (
	MemberID INTEGER PRIMARY KEY NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Gender Gender NOT NULL,
	EmailAddress VARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(100) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	Age INTEGER NOT NULL,
	TypeOfMembership VARCHAR(100) NOT NULL,
	DateOfMembership DATE NOT NULL,
	Status MemberStatus NOT NULL
);



CREATE TABLE IF NOT EXISTS Departments (
	DeptID INTEGER PRIMARY KEY NOT NULL,
	DepartmentName VARCHAR(100) NOT NULL,
	ManagerName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS LibraryStaff (
	StaffID INTEGER PRIMARY KEY NOT NULL,
	Name VARCHAR(100) NOT NULL,
	JobTitle VARCHAR(100) NOT NULL,
	DepartmentID INTEGER REFERENCES Departments(DeptID) ON DELETE SET NULL,
	Gender Gender NOT NULL,
	Address VARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(100) NOT NULL,
	HireDate DATE NOT NULL,
	ManagerID INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS BorrowHistory (
	BorrowedID INTEGER PRIMARY KEY NOT NULL,
	BookID INTEGER REFERENCES Books(BookID) ON DELETE SET NULL,
	MemberID INTEGER REFERENCES Members(MemberID) ON DELETE SET NULL,
	BorrowDate DATE NOT NULL,
	ReturnDate DATE 
);

ALTER TABLE BorrowHistory
ALTER ReturnDate DROP NOT NULL;


CREATE TABLE IF NOT EXISTS BookOrders (
	OrderID INTEGER PRIMARY KEY NOT NULL,
	OrderDate DATE NOT NULL,
	BookID INTEGER REFERENCES Books(BookID) ON DELETE SET NULL,
	Cost DECIMAL(5,2) NOT NULL,
	Quantity INTEGER NOT NULL,
	SupplyDate DATE NOT NULL,
	FulfillmentStatus FulfillmentStatus NOT NULL,
	SupplierName VARCHAR(100) NOT NULL
);
